### PR TITLE
Move phpunit to require-dev

### PR DESCRIPTION
**Pull request by EdwardCaulfield**

### CODE REVIEW

**Comment by EdwardCaulfield** [comment]
Our team prefers not to have phpunit in production code.

**Comment by sadamczyk** [comment]
@EdwardCaulfield I suggested this change in the last sentence of https://github.com/kmukku/php-iso11649/issues/5, so thanks for making a PR for this! :)
Would you be able to test if a downgrade of phpunit to version `^4.8` breaks the current tests?
Because then that whole issue could be resolved as well.

**Comment by EdwardCaulfield** [comment]
> Would you be able to test if a downgrade of phpunit to version `^4.8` breaks the current tests?  

No, I am not in a position to do that.

**Comment by kmukku** [comment]
Seems legit. If you guys want to collaborate with this repo, I'm happy to add. I have no use for this myself anymore and haven't use PHP for a while.

**Pull request merged**
